name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      Azure_terraform_practice:
        description: Azure Terraform practice
        required: true
        type: choice
        options:
          - Azure-VNet
          - Azure-Storage-Account
          - Azure-NSG-Security-Group
          - Azure-Load-Balancer
          - Azure-SQL-Database
          - Azure-VM-With-Public-IP
          - Azure-VM-Without-Public-IP

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'

      - name: Terraform Init
        working-directory: ${{ github.workspace }}/${{ inputs.terraform_folder }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ github.workspace }}/${{ inputs.terraform_folder }}
        run: terraform plan

      - name: Terraform Apply
        working-directory: ${{ github.workspace }}/${{ inputs.terraform_folder }}
        run: terraform apply -auto-approve
